### ISSUE TITLE
Task #3276 for LeadWires v1.1.10 generated an exception

### ISSUE THREAD

**Issue by JerryTheSlime16** [saharNooby/lead-wires#9]
The following spams console.

```
[00:23:05 WARN]: [LeadWires] Task #3276 for LeadWires v1.1.10 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315) ~[ProtocolLib.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn_1_17(ProtocolUtil.java:186) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn(ProtocolUtil.java:171) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTracker.checkPlayer(WireTracker.java:128) ~[LeadWires.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTracker.checkAllPlayers(WireTracker.java:184) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.LeadWires.lambda$onEnable$0(LeadWires.java:83) ~[LeadWires.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

Paper version:
```
Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-2118 (MC: 1.20.4)
* You are running the latest version
```
LeadWires Version: `1.1.10`
ProtocolLib Version: `5.2.1-SNAPSHOT-689`

Please let me know what other information is needed.

**Comment by LedariaTim1** [comment]
Hi,
try ProtocolLib 5.2.0, the newer versions are only compatible for 1.20.6 and 1.21

It may also be due to Purpur, I always test  only with papermc

**Comment by JerryTheSlime16** [comment]
Hey, sorry for the delayed response. I've updated ProtocolLib to 5.3.0 (most recent as of this reply). Here is what's in console. I know we aren't using the ideal server version, so if you don't have a fix, that's fine. Thanks.

```
[21:00:58 ERROR]: Could not pass event ChunkUnloadSentEvent to LeadWires v1.1.10
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn_1_17(ProtocolUtil.java:186) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn(ProtocolUtil.java:171) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTracker.onChunkUnloadSent(WireTracker.java:62) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTrackerListener.lambda$onChunkUnloadSent$2(WireTrackerListener.java:49) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTrackerListener.doInMainThread(WireTrackerListener.java:66) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTrackerListener.onChunkUnloadSent(WireTrackerListener.java:49) ~[LeadWires.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor456.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at me.saharnooby.plugins.leadwires.chunk.LoadedChunkTracker.onPacketSending(LoadedChunkTracker.java:108) ~[LeadWires.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:276) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:261) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.network.PlayerChunkSender.dropChunkStatic(PlayerChunkSender.java:48) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendUnloadChunkRaw(RegionizedPlayerChunkLoader.java:497) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendUnloadChunk(RegionizedPlayerChunkLoader.java:493) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData$1.removeCallback(RegionizedPlayerChunkLoader.java:508) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData$1.removeCallback(RegionizedPlayerChunkLoader.java:500) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.util.player.SingleUserAreaMap.removeFromOld(SingleUserAreaMap.java:44) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.util.player.SingleUserAreaMap.update(SingleUserAreaMap.java:91) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.update(RegionizedPlayerChunkLoader.java:976) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:242) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:500) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:876) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[21:01:02 WARN]: [LeadWires] Task #90 for LeadWires v1.1.10 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn_1_17(ProtocolUtil.java:186) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.ProtocolUtil.despawn(ProtocolUtil.java:171) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTracker.checkPlayer(WireTracker.java:128) ~[LeadWires.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at me.saharnooby.plugins.leadwires.tracker.WireTracker.checkAllPlayers(WireTracker.java:184) ~[LeadWires.jar:?]
        at me.saharnooby.plugins.leadwires.LeadWires.lambda$onEnable$0(LeadWires.java:83) ~[LeadWires.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
